---
title: "p8105_hw2_crd2162"
author: "Caleigh Dwyer"
date: "2023-09-26"
output: github_document
---

```{r load library}
library(tidyverse)
```

## Problem 1: Cleaning and merging FiveThiryEight data

In the chunk below, we will clean the data in pols-month.csv. This data 

```{r pols cleaning}
pols_df =
  read_csv("data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(col = mon, into = c("year","month","day"), sep = "-") |> 
  mutate(
    month = recode(
      month,
      "01" = "january",
      "02" = "february",
      "03" ="march",
      "04" ="april",
      "05" ="may",
      "06" ="june",
      "07" ="july",
      "08" ="august",
      "09" ="september",
      "10" ="october",
      "11" ="november",
      "12" = "december")) |> 
  mutate(
    president =
      case_when (prez_gop %in% c(1,2) ~ "gop",
                 prez_dem == 1 ~ "dem")) |> 
  select(-prez_gop, -prez_dem, -day)
  

view(pols_df)
```

In the chunk below, we will clean the data in snp.csv

```{r snp cleaning}
snp_df =
  read_csv("data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(col = date, into = c("year","month","day"), sep = "/")|> 
  mutate(
    month = recode(
      month,
      "1" = "january",
      "2" = "february",
      "3" ="march",
      "4" ="april",
      "5" ="may",
      "6" ="june",
      "7" ="july",
      "8" ="august",
      "9" ="september",
      "10" ="october",
      "11" ="november",
      "12" = "december"))|>
  mutate(
    year = recode(
      year,
      "1" = "01",
      "2" = "02",
      "3" = "03",
      "4" = "04",
      "5" = "05",
      "6" = "06",
      "7" = "07",
      "8" = "08",
      "9" = "09")
      ) |> 
  year <- ifelse(as.integer(year) >= 47, 
                    paste("19", abbreviated_year, sep = ""), 
                    paste("20", abbreviated_year, sep = ""))
##figure out range of years for snp_df and then create threshold based off that.
  select(-day)
view(snp_df)
```

In the chunk below, we will clean the data in unemployment.csv


```{r unemployment cleaning}
unemployment_df =
  read_csv("data/unemployment.csv") |> 
  janitor::clean_names()
```

